require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe Admin::BuildingsController do

  # This should return the minimal set of attributes required to create a valid
  # Admin::Building. As you add validations to Admin::Building, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {  } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # Admin::BuildingsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all admin_buildings as @admin_buildings" do
      building = Admin::Building.create! valid_attributes
      get :index, {}, valid_session
      assigns(:admin_buildings).should eq([building])
    end
  end

  describe "GET show" do
    it "assigns the requested admin_building as @admin_building" do
      building = Admin::Building.create! valid_attributes
      get :show, {:id => building.to_param}, valid_session
      assigns(:admin_building).should eq(building)
    end
  end

  describe "GET new" do
    it "assigns a new admin_building as @admin_building" do
      get :new, {}, valid_session
      assigns(:admin_building).should be_a_new(Admin::Building)
    end
  end

  describe "GET edit" do
    it "assigns the requested admin_building as @admin_building" do
      building = Admin::Building.create! valid_attributes
      get :edit, {:id => building.to_param}, valid_session
      assigns(:admin_building).should eq(building)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Admin::Building" do
        expect {
          post :create, {:admin_building => valid_attributes}, valid_session
        }.to change(Admin::Building, :count).by(1)
      end

      it "assigns a newly created admin_building as @admin_building" do
        post :create, {:admin_building => valid_attributes}, valid_session
        assigns(:admin_building).should be_a(Admin::Building)
        assigns(:admin_building).should be_persisted
      end

      it "redirects to the created admin_building" do
        post :create, {:admin_building => valid_attributes}, valid_session
        response.should redirect_to(Admin::Building.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved admin_building as @admin_building" do
        # Trigger the behavior that occurs when invalid params are submitted
        Admin::Building.any_instance.stub(:save).and_return(false)
        post :create, {:admin_building => {  }}, valid_session
        assigns(:admin_building).should be_a_new(Admin::Building)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Admin::Building.any_instance.stub(:save).and_return(false)
        post :create, {:admin_building => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested admin_building" do
        building = Admin::Building.create! valid_attributes
        # Assuming there are no other admin_buildings in the database, this
        # specifies that the Admin::Building created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Admin::Building.any_instance.should_receive(:update).with({ "these" => "params" })
        put :update, {:id => building.to_param, :admin_building => { "these" => "params" }}, valid_session
      end

      it "assigns the requested admin_building as @admin_building" do
        building = Admin::Building.create! valid_attributes
        put :update, {:id => building.to_param, :admin_building => valid_attributes}, valid_session
        assigns(:admin_building).should eq(building)
      end

      it "redirects to the admin_building" do
        building = Admin::Building.create! valid_attributes
        put :update, {:id => building.to_param, :admin_building => valid_attributes}, valid_session
        response.should redirect_to(building)
      end
    end

    describe "with invalid params" do
      it "assigns the admin_building as @admin_building" do
        building = Admin::Building.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Admin::Building.any_instance.stub(:save).and_return(false)
        put :update, {:id => building.to_param, :admin_building => {  }}, valid_session
        assigns(:admin_building).should eq(building)
      end

      it "re-renders the 'edit' template" do
        building = Admin::Building.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Admin::Building.any_instance.stub(:save).and_return(false)
        put :update, {:id => building.to_param, :admin_building => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested admin_building" do
      building = Admin::Building.create! valid_attributes
      expect {
        delete :destroy, {:id => building.to_param}, valid_session
      }.to change(Admin::Building, :count).by(-1)
    end

    it "redirects to the admin_buildings list" do
      building = Admin::Building.create! valid_attributes
      delete :destroy, {:id => building.to_param}, valid_session
      response.should redirect_to(admin_buildings_url)
    end
  end

end
